# Site settings
title: tony schick
email: schick.anthony@gmail.com
description: "journalism
data
design"
baseurl: ""
twitter_username: tonyvschick
github_username:  tonyschick
public_key: 'http://pgp.mit.edu/pks/lookup?op=get&search=0xE3A41916D23BA9B1'

# Build settings
markdown: kramdown
permalink: pretty
